const DEVOCIONAL = [
    { title: "devocionalHoy", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/Devocionales/devocionalHoy.mp3" },
    { title: "devocionalHoy2", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/Devocionales/devocionalHoy2.mp3" },
    { title: "devocionalHoy3", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/Devocionales/devocionalHoy3.mp3" },
];
const CRISTIANS = [
    { title: "Si tu voluntad duele", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/Music/Si%20tu%20voluntad%20duele.mp3" },
    { title: "Nunca me dejarás", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/Music/Nunca%20me%20dejar%C3%A1s.mp3" },
    { title: "Sorprendeme Dios", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/Music/Sorprendeme%20Dios.mp3" },
    { title: "En sus manos está", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/Music/En%20sus%20manos%20está.mp3" },
    { title: "Tu proveerás", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/Music/Tu%20proveerás.mp3" }
];
const MIAS = [
    { title: "EL QUE NO DUERME v1", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/Music/EL%20QUE%20NO%20DUERME%20v1.mp3" },
    { title: "Contigo todo pesa menos", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/Music/Contigo%20todo%20pesa%20menos.mp3" },
    { title: "EL QUE NO DUERME v2", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/Music/EL%20QUE%20NO%20DUERME%20v2.mp3" },
    { title: "El desorden perfecto", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/Music/El%20desorden%20perfecto.mp3" },
    { title: "El reloj se para", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/Music/El%20reloj%20se%20para.mp3" },
    { title: "El tamaño de tu mano", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/Music/El%20tama%C3%B1o%20de%20tu%20mano.mp3" },
    { title: "Mi lugar en el mundo", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/Music/Mi%20lugar%20en%20el%20mundo.mp3" },
    { title: "Mi princesa", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/Music/Mi%20princesa.mp3" },
    { title: "También sus espinas", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/Music/Tambi%C3%A9n%20sus%20espinas.mp3" },
    { title: "Te amo", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/Music/Te%20amo.mp3" },
    { title: "Todavía me sorprende", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/Music/Todav%C3%ADa%20me%20sorprende.mp3" },
    { title: "Tu nombre es mi respiración", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/Music/Tu%20nombre%20es%20mi%20respiraci%C3%B3n.mp3" },
    { title: "Mi lugar favorito", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/Music/Mi%20lugar%20favorito.mp3" }
];

const GYM = [
    { title: "Adrenalina hard techno rave", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/adrenalina%20%20hard%20techno%20rave.mp3" },
    { title: "Alessia Cara - Here", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/alessia%20cara%20-%20here.mp3" },
    { title: "Ballintekk", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/ballintekk.mp3" },
    { title: "Billie Eilish - L'amour de ma vie", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/billie%20eilish%20-%20lamour%20de%20ma%20vie.mp3" },
    { title: "Boney M. - Rasputin", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/boney%20m.%20-%20rasputin.mp3" },
    { title: "Bring Me The Horizon - Can You Feel My Heart", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/can%20you%20feel%20my%20heart%20-%20bring%20me%20the%20horizon.mp3" },
    { title: "Michael Jackson - Chicago", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/chicago%20-%20michael%20jackson.mp3" },
    { title: "Danny - Take Me", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/d%20a%20n%20n%20y%20-%20take%20me.mp3" },
    { title: "Esta canción da mucha aura", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/esta%20cancion%20da%20mucha%20aura.mp3" },
    { title: "First Blood", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/first%20blood.mp3" },
    { title: "Fujii Kaze - Shinunoga E-Wa", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/fujii%20kaze%20-%20shinunoga%20e-wa.mp3" },
    { title: "Hard Techno - Voices In My Head", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/hard%20techno%20%20voices%20in%20my%20head.mp3" },
    { title: "Infeed - Freedom Inside Your Illness", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/infeed%20-%20freedom%20inside%20your%20illness.mp3" },
    { title: "Jeremy Zucker - Comethru", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/jeremy%20zucker%20-%20comethru.mp3" },
    { title: "Josean Log - Kaguya-sama Love Is War", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/kaguya-sama_%20love%20is%20waramvdoma%20%20josean%20log.mp3" },
    { title: "Kehlani - Gangsta", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/kehlani%20-%20gangsta.mp3" },
    { title: "Kordhell - Murder In My Mind (Speed Up)", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/kordhell%20-%20murder%20in%20my%20mind%20%20speed%20up.mp3" },
    { title: "MTG Chihiro", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/mtg%20chihiro.mp3" },
    { title: "Ogryzek - Aura", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/ogryzek%20-%20aura.mp3" },
    { title: "Olivia Rodrigo - Honeybee", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/olivia%20rodrigo%20-%20honeybee.mp3" },
    { title: "Skillet - Hero", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/skillet%20-%20hero.mp3" },
    { title: "Skillet - Monster", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/skillet%20-%20monster.mp3" },
    { title: "Skillet - Not Gonna Die", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/skillet%20-%20not%20gonna%20die.mp3" },
    { title: "Skrillex - Bangarang (feat. Sirah)", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/skrillex%20-%20bangarang%20feat.%20sirah.mp3" },
    { title: "Skrillex - First Of The Year", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/skrillex%20-%20first%20of%20the%20year.mp3" },
    { title: "Skrillex - Kyoto", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/skrillex%20-%20kyoto.mp3" },
    { title: "Skrillex - Rock N Roll", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/skrillex%20-%20rock%20n%20roll.mp3" },
    { title: "Skrillex & Damian Jr. Gong Marley - Make It Bun Dem", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/skrillex%20and%20damian%20jr.%20gong%20marley%20-%20make%20it%20bun%20dem.mp3" },
    { title: "Super Smash Bros Brawl Drill Remix - By Shae OT", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/super%20smash%20bros%20brawl%20drill%20remix%20%20by%20shae%20ot.mp3" },
    { title: "Tell Em x Killin On Demand (TikTok)", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/tell%20em%20x%20killin%20on%20demand%20tiktok.mp3" },
    { title: "Twenty One Pilots - Heathens", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/twenty%20one%20pilots%20-%20heathens.mp3" },
    { title: "Unaverage Gang - Underworld", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/unaverage%20gang%20-%20underworld.mp3" },
    { title: "Xvallarix - Ballintekk", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/xvallarix%20-%20ballintekk.mp3" },
    { title: "ACDC - BACK IN BLACK", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/acdc%20-%20back%20in%20black.mp3" },
    { title: "Armin van Buuren - Turn It Up.mp3", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/armin%20van%20buuren%20-%20turn%20it%20up.mp3" },
    { title: "Bel Mercy feat. Nokia.mp3", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/bel%20mercy%20feat.%20nokia.mp3" },
    { title: "Bel Mercy.mp3", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/bel%20mercy.mp3" },
    { title: "Benny Benassi - Satisfaction.mp3", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/benny%20benassi%20-%20satisfaction.mp3" },
    { title: "Black Eyed Peas - My Humps.mp3", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/black%20eyed%20peas%20-%20my%20humps.mp3" },
    { title: "FOVOS - Feel The Rhythm.mp3", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/fovos%20-%20feel%20the%20rhythm.mp3" },
    { title: "Gonzi - BASSKILLER.mp3", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/gonzi%20-%20basskiller.mp3" },
    { title: "Guns N Roses - Welcome To The Jungle.mp3", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/guns%20n%20roses%20-%20welcome%20to%20the%20jungle.mp3" },
    { title: "KISS  I Was Made For Lovin You.mp3", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/kiss%20i%20was%20made%20for%20lovin%20you.mp3" },
    { title: "LICK IT.mp3", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/lick%20it.mp3" },
    { title: "Maneskin - MAMMAMIA.mp3", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/maneskin%20-%20mammamia.mp3" },
    { title: "Måneskin - GOSSIP ft. Tom Morello Sub español  Lyrics.mp3", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/maaneskin%20-%20gossip%20ft.%20tom%20morello%20sub%20español%20lyrics.mp3" },
    { title: "Not Broken  CortexUS.mp3", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/not%20broken%20cortexus.mp3" },
    { title: "Rammstein - Du Hast.mp3", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/rammstein%20-%20du%20hast.mp3" },
    { title: "Sweet Child O Mine.mp3", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/sweet%20child%20o'%20mine.mp3" },
    { title: "TECHNO  NO BATIDA.mp3", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/techno%20no%20batida.mp3" },
    { title: "The Black Eyed Peas - The Time.mp3", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/the%20black%20eyed%20peas%20-%20the%20time.mp3" },
    { title: "Toby DEE, Tony Richard, SANE - Toccata.mp3", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/toby%20dee,%20tony%20richard,%20sane%20-%20toccata.mp3" }
];