const CRISTIANS = [
    { title: "Si tu voluntad duele", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/Music/Si%20tu%20voluntad%20duele.mp3" },
    { title: "Nunca me dejarás", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/Music/Nunca%20me%20dejar%C3%A1s.mp3" },
    { title: "Sorprendeme Dios", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/Music/Sorprendeme%20Dios.mp3" },
    { title: "En sus manos está", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/Music/En%20sus%20manos%20está.mp3" },
    { title: "Tu proveerás", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/Music/Tu%20proveerás.mp3" },
    { title: "Mis planes en tus manos está", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/Music/Mis%20planes%20en%20tus%20manos%20está.mp3" },
    { title: "Duo noe y ruth campos la manana gloriosa", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/Music/Duo%20noe%20y%20ruth%20campos%20la%20manana%20gloriosa.mp3" },
    { title: "Guiame tú", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/Music/Guiame%20tú.mp3" },
    { title: "A la sombra de tus alas version alternativa deep hause mlavida", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/A%20la%20sombra%20de%20tus%20alas%20version%20alternativa%20deep%20hause%20mlavida.mp3" },
    { title: "A quien ire", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/A%20quien%20ire.mp3" },
    { title: "A ti", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/A%20ti.mp3" },
    { title: "A tiempo", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/A%20tiempo.mp3" },
    { title: "Admirable consejero", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Admirable%20consejero.mp3" },
    { title: "Agradecido", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Agradecido.mp3" },
    { title: "Ahi estaba cristo", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Ahi%20estaba%20cristo.mp3" },
    { title: "Alaba a dios", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Alaba%20a%20dios.mp3" },
    { title: "Alfa y omega", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Alfa%20y%20omega.mp3" },
    { title: "Bajo tu amor", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Bajo%20tu%20amor.mp3" },
    { title: "Bendito amor", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Bendito%20amor.mp3" },
    { title: "Bienvenido a bordo", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Bienvenido%20a%20bordo.mp3" },
    { title: "Bueno es alabarte senor danilo montero", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Bueno%20es%20alabarte%20senor%20danilo%20montero.mp3" },
    { title: "Cambiaste mi corazon", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Cambiaste%20mi%20corazon.mp3" },
    { title: "Causas perdidas feat ulises eyherabide", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Causas%20perdidas%20feat%20ulises%20eyherabide.mp3" },
    { title: "De buenas", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/De%20buenas.mp3" },
    { title: "De ti dependo", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/De%20ti%20dependo.mp3" },
    { title: "Dios de imposibles", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Dios%20de%20imposibles.mp3" },
    { title: "Dios ha sido bueno down", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Dios%20ha%20sido%20bueno%20down.mp3" },
    { title: "Donde nadie escucha dios oye", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Donde%20nadie%20escucha%20dios%20oye.mp3" },
    { title: "El fuego ardera cuan grande es el he decidido seguir a cristo", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/El%20fuego%20ardera%20cuan%20grande%20es%20el%20he%20decidido%20seguir%20a%20cristo.mp3" },
    { title: "El fuego ardera", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/El%20fuego%20ardera.mp3" },
    { title: "El mismo dios", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/El%20mismo%20dios.mp3" },
    { title: "En hora buena", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/En%20hora%20buena.mp3" },
    { title: "Enviame a mi", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Enviame%20a%20mi.mp3" },
    { title: "Es perfecto", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Es%20perfecto.mp3" },
    { title: "Esperame", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Esperame.mp3" },
    { title: "Evan craft y paula prieto cuan dulce paz", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Evan%20craft%20y%20paula%20prieto%20cuan%20dulce%20paz.mp3" },
    { title: "Fiel", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Fiel.mp3" },
    { title: "Fiesta en el desierto dj ados music", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Fiesta%20en%20el%20desierto%20dj%20ados%20music.mp3" },
    { title: "Fuerzas pa", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Fuerzas%20pa.mp3" },
    { title: "Ganas de vivir camino de vida", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Ganas%20de%20vivir%20camino%20de%20vida.mp3" },
    { title: "Ganas de vivir", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Ganas%20de%20vivir.mp3" },
    { title: "Gozo pegajoso", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Gozo%20pegajoso.mp3" },
    { title: "Gracia incomparable version", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Gracia%20incomparable%20version.mp3" },
    { title: "Gracia sublime es en espiritu y en verdad", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Gracia%20sublime%20es%20en%20espiritu%20y%20en%20verdad.mp3" },
    { title: "Gracias", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Gracias.mp3" },
    { title: "Hay libertad", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Hay%20libertad.mp3" },
    { title: "Hermoso momento", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Hermoso%20momento.mp3" },
    { title: "Indudablemente", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Indudablemente.mp3" },
    { title: "Jay kalyl mil razones version", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Jay%20kalyl%20mil%20razones%20version.mp3" },
    { title: "Jesucristo basta version", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Jesucristo%20basta%20version.mp3" },
    { title: "Jesus has mi caracter", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Jesus%20has%20mi%20caracter.mp3" },
    { title: "La bondad de dios", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/La%20bondad%20de%20dios.mp3" },
    { title: "La casa de dios", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/La%20casa%20de%20dios.mp3" },
    { title: "La milla extra", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/La%20milla%20extra.mp3" },
    { title: "La nina de tus ojos piano feat firmeza", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/La%20nina%20de%20tus%20ojos%20piano%20feat%20firmeza.mp3" },
    { title: "Mas que un anhelo", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Mas%20que%20un%20anhelo.mp3" },
    { title: "Mas que vencedor", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Mas%20que%20vencedor.mp3" },
    { title: "Matematicas", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Matematicas.mp3" },
    { title: "Me enamore", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Me%20enamore.mp3" },
    { title: "Me llamas", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Me%20llamas.mp3" },
    { title: "Mesias ven de adoracion feat naiara cano", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Mesias%20ven%20de%20adoracion%20feat%20naiara%20cano.mp3" },
    { title: "Mi casa y yo", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Mi%20casa%20y%20yo.mp3" },
    { title: "No me dejaras", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/No%20me%20dejaras.mp3" },
    { title: "No te rindas", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/No%20te%20rindas.mp3" },
    { title: "No vuelvo pa tras", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/No%20vuelvo%20pa%20tras.mp3" },
    { title: "Ofrenda", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Ofrenda.mp3" },
    { title: "Pentagrama", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Pentagrama.mp3" },
    { title: "Perfecto amor", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Perfecto%20amor.mp3" },
    { title: "Por conocerte", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Por%20conocerte.mp3" },
    { title: "Quedate", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Quedate.mp3" },
    { title: "Quien soy yo", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Quien%20soy%20yo.mp3" },
    { title: "Redimi2 blindao", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Redimi2%20blindao.mp3" },
    { title: "Regresanos version regional", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Regresanos%20version%20regional.mp3" },
    { title: "Regreso a ti", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Regreso%20a%20ti.mp3" },
    { title: "Respira", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Respira.mp3" },
    { title: "Santiago benavides gracias por pedro", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Santiago%20benavides%20gracias%20por%20pedro.mp3" },
    { title: "Sentidos", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Sentidos.mp3" },
    { title: "Serendipia", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Serendipia.mp3" },
    { title: "Si no estas tu", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Si%20no%20estas%20tu.mp3" },
    { title: "Simplicidad", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Simplicidad.mp3" },
    { title: "Solo tu", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Solo%20tu.mp3" },
    { title: "Suelto", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Suelto.mp3" },
    { title: "Te he visto fiel", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Te%20he%20visto%20fiel.mp3" },
    { title: "Te luciste", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Te%20luciste.mp3" },
    { title: "Te quiero te quiero version", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Te%20quiero%20te%20quiero%20version.mp3" },
    { title: "Todo empezo feat funky", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Todo%20empezo%20feat%20funky.mp3" },
    { title: "Todo va a estar bien", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Todo%20va%20a%20estar%20bien.mp3" },
    { title: "Tu me llamas", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Tu%20me%20llamas.mp3" },
    { title: "Tu mirada hermoso eres", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Tu%20mirada%20hermoso%20eres.mp3" },
    { title: "Tu mirada", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Tu%20mirada.mp3" },
    { title: "Tu voz", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Tu%20voz.mp3" },
    { title: "Venga tu reino hillsong en espanol espanol", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Venga%20tu%20reino%20hillsong%20en%20espanol%20espanol.mp3" },
    { title: "Vive salsa", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Vive%20salsa.mp3" },
    { title: "Vives tu y vivo yo", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Vives%20tu%20y%20vivo%20yo.mp3" },
    { title: "Vivir el cielo", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Vivir%20el%20cielo.mp3" },
    { title: "Vivire", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Vivire.mp3" },
    { title: "Yo quiero amarte mas", url: "https://raw.githubusercontent.com/bryan7896/musica1/main/Yo%20quiero%20amarte%20mas.mp3" },
    { title: "A ti sea la gloria ft marcela gandara", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/A%20ti%20sea%20la%20gloria%20ft%20marcela%20gandara.mp3" },
    { title: "Agua en el desierto", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Agua%20en%20el%20desierto.mp3" },
    { title: "Amores como el tuyo", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Amores%20como%20el%20tuyo.mp3" },
    { title: "Anhelo tu presencia", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Anhelo%20tu%20presencia.mp3" },
    { title: "Ayer y hoy", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Ayer%20y%20hoy.mp3" },
    { title: "Babel", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Babel.mp3" },
    { title: "Busco", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Busco.mp3" },
    { title: "Cantare de tu amor", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Cantare%20de%20tu%20amor.mp3" },
    { title: "Cara a cara te deseo", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Cara%20a%20cara%20te%20deseo.mp3" },
    { title: "Cierra la puerta", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Cierra%20la%20puerta.mp3" },
    { title: "Confiare en tus promesas", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Confiare%20en%20tus%20promesas.mp3" },
    { title: "Contigo justo a tiempo", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Contigo%20justo%20a%20tiempo.mp3" },
    { title: "Contigo quiero caminar", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Contigo%20quiero%20caminar.mp3" },
    { title: "Creere", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Creere.mp3" },
    { title: "Dame un nuevo corazon", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Dame%20un%20nuevo%20corazon.mp3" },
    { title: "Derrama de tu fuego", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Derrama%20de%20tu%20fuego.mp3" },
    { title: "Desesperado espanol", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Desesperado%20espanol.mp3" },
    { title: "Digno es el senor marcela gandara", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Digno%20es%20el%20senor%20marcela%20gandara.mp3" },
    { title: "El brillo de mis ojos", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/El%20brillo%20de%20mis%20ojos.mp3" },
    { title: "El dios de abraham", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/El%20dios%20de%20abraham.mp3" },
    { title: "El milagro", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/El%20milagro.mp3" },
    { title: "El nombre de jesus", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/El%20nombre%20de%20jesus.mp3" },
    { title: "El padre que siempre sone", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/El%20padre%20que%20siempre%20sone.mp3" },
    { title: "En la cruz", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/En%20la%20cruz.mp3" },
    { title: "En los montes en los valles", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/En%20los%20montes%20en%20los%20valles.mp3" },
    { title: "Eres mi bendicion feat alex zurdo", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Eres%20mi%20bendicion%20feat%20alex%20zurdo.mp3" },
    { title: "Eres mi paz", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Eres%20mi%20paz.mp3" },
    { title: "Eres todopoderoso bonus track", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Eres%20todopoderoso%20bonus%20track.mp3" },
    { title: "Eres", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Eres.mp3" },
    { title: "Es imposible", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Es%20imposible.mp3" },
    { title: "Escuche la voz", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Escuche%20la%20voz.mp3" },
    { title: "Eternamente amor", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Eternamente%20amor.mp3" },
    { title: "Eterno es tu amor", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Eterno%20es%20tu%20amor.mp3" },
    { title: "Gracias tu fidelidad", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Gracias%20tu%20fidelidad.mp3" },
    { title: "Gratitud", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Gratitud.mp3" },
    { title: "Halle un buen amigo", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Halle%20un%20buen%20amigo.mp3" },
    { title: "He decidido seguir a cristo", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/He%20decidido%20seguir%20a%20cristo.mp3" },
    { title: "Hosanna", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Hosanna.mp3" },
    { title: "Impulso", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Impulso.mp3" },
    { title: "Increible feat evan craft", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Increible%20feat%20evan%20craft.mp3" },
    { title: "Inunda este lugar", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Inunda%20este%20lugar.mp3" },
    { title: "Jesus eres mi buen pastor", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Jesus%20eres%20mi%20buen%20pastor.mp3" },
    { title: "Jesus", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Jesus.mp3" },
    { title: "La carrera", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/La%20carrera.mp3" },
    { title: "La fruta prohibida", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/La%20fruta%20prohibida.mp3" },
    { title: "Llevame a tu presencia", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Llevame%20a%20tu%20presencia.mp3" },
    { title: "Lo unico que quiero sesion organica", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Lo%20unico%20que%20quiero%20sesion%20organica.mp3" },
    { title: "Lo unico que quiero", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Lo%20unico%20que%20quiero.mp3" },
    { title: "Mas rico del mundo", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Mas%20rico%20del%20mundo.mp3" },
    { title: "Me devolviste la vida", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Me%20devolviste%20la%20vida.mp3" },
    { title: "Me encontraste", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Me%20encontraste.mp3" },
    { title: "Me quemas", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Me%20quemas.mp3" },
    { title: "Me sostiene", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Me%20sostiene.mp3" },
    { title: "Mejor contigo", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Mejor%20contigo.mp3" },
    { title: "Miles de canciones", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Miles%20de%20canciones.mp3" },
    { title: "Nadie como tu", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Nadie%20como%20tu.mp3" },
    { title: "No hay nada imposible", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/No%20hay%20nada%20imposible.mp3" },
    { title: "Principio y fin version", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Principio%20y%20fin%20version.mp3" },
    { title: "Promesas", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Promesas.mp3" },
    { title: "Pura alegria", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Pura%20alegria.mp3" },
    { title: "Que pase el mundo", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Que%20pase%20el%20mundo.mp3" },
    { title: "Quien como el", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Quien%20como%20el.mp3" },
    { title: "Razones pa vivir feat alex campos", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Razones%20pa%20vivir%20feat%20alex%20campos.mp3" },
    { title: "Regresanos", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Regresanos.mp3" },
    { title: "Rey", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Rey.mp3" },
    { title: "Santo por siempre", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Santo%20por%20siempre.mp3" },
    { title: "Si tu presencia conmigo no va", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Si%20tu%20presencia%20conmigo%20no%20va.mp3" },
    { title: "Sin ti", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Sin%20ti.mp3" },
    { title: "Sin tu amor feat alex zurdo", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Sin%20tu%20amor%20feat%20alex%20zurdo.mp3" },
    { title: "Socorro", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Socorro.mp3" },
    { title: "Sublime gracia", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Sublime%20gracia.mp3" },
    { title: "Supe que me amabas", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Supe%20que%20me%20amabas.mp3" },
    { title: "Te amo espiritu santo", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Te%20amo%20espiritu%20santo.mp3" },
    { title: "Tengo un dios", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Tengo%20un%20dios.mp3" },
    { title: "Todo lo has cambiado", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Todo%20lo%20has%20cambiado.mp3" },
    { title: "Todo lo puedo", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Todo%20lo%20puedo.mp3" },
    { title: "Tu amor hace eco en todo mi universo version remasterizada", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Tu%20amor%20hace%20eco%20en%20todo%20mi%20universo%20version%20remasterizada.mp3" },
    { title: "Tu amor", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Tu%20amor.mp3" },
    { title: "Tu bandera", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Tu%20bandera.mp3" },
    { title: "Tu nos salvaras", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Tu%20nos%20salvaras.mp3" },
    { title: "Tu tan mio", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Tu%20tan%20mio.mp3" },
    { title: "Tus planes", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Tus%20planes.mp3" },
    { title: "Un cantico nuevo", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Un%20cantico%20nuevo.mp3" },
    { title: "Una nueva cancion", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Una%20nueva%20cancion.mp3" },
    { title: "Ven te necesito ft lilly goodman", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Ven%20te%20necesito%20ft%20lilly%20goodman.mp3" },
    { title: "Viaje perfecto", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Viaje%20perfecto.mp3" },
    { title: "Vida encontre", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Vida%20encontre.mp3" },
    { title: "Viento de dios sopla aqui cancion soulblues del valle seco musicacristiana soulblues", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Viento%20de%20dios%20sopla%20aqui%20cancion%20soulblues%20del%20valle%20seco%20musicacristiana%20soulblues.mp3" },
    { title: "Ya no soy igual", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Ya%20no%20soy%20igual.mp3" },
    { title: "Yo me rindo a el", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Yo%20me%20rindo%20a%20el.mp3" },
    { title: "Yo tengo un nuevo amor", url: "https://raw.githubusercontent.com/bryan7896/musica2/main/Yo%20tengo%20un%20nuevo%20amor.mp3" },
    { title: "A el sea la gloria", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/A%20el%20sea%20la%20gloria.mp3" },
    { title: "Al taller del maestro", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Al%20taller%20del%20maestro.mp3" },
    { title: "Alaba praise", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Alaba%20praise.mp3" },
    { title: "Arde en mi", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Arde%20en%20mi.mp3" },
    { title: "Averly morillo quien podra drill", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Averly%20morillo%20quien%20podra%20drill.mp3" },
    { title: "Bendito jesus", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Bendito%20jesus.mp3" },
    { title: "Bueno es dios", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Bueno%20es%20dios.mp3" },
    { title: "Cadena rota blues gospel vol 1", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Cadena%20rota%20blues%20gospel%20vol%201%20%C2%B6.mp3" },
    { title: "Cara a cara", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Cara%20a%20cara.mp3" },
    { title: "Como el color de la sangre", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Como%20el%20color%20de%20la%20sangre.mp3" },
    { title: "Como luz llego", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Como%20luz%20llego.mp3" },
    { title: "Como tu no hay", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Como%20tu%20no%20hay.mp3" },
    { title: "Corazon limpio salmo 51 con y acordes", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Corazon%20limpio%20salmo%2051%20con%20y%20acordes.mp3" },
    { title: "Cuando yo te conoci", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Cuando%20yo%20te%20conoci.mp3" },
    { title: "Dame de beber", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Dame%20de%20beber.mp3" },
    { title: "Danzando nadie como tu", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Danzando%20nadie%20como%20tu.mp3" },
    { title: "Dios cuida de mi", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Dios%20cuida%20de%20mi.mp3" },
    { title: "Dios ha sido bueno", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Dios%20ha%20sido%20bueno.mp3" },
    { title: "Dios hablame", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Dios%20hablame.mp3" },
    { title: "Donde estaria", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Donde%20estaria.mp3" },
    { title: "El poder de la oracion", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/El%20poder%20de%20la%20oracion.mp3" },
    { title: "Empezar de nuevo", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Empezar%20de%20nuevo.mp3" },
    { title: "Es por tu gracia", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Es%20por%20tu%20gracia.mp3" },
    { title: "Espiritu santo", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Espiritu%20santo.mp3" },
    { title: "Estoy tranquilo", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Estoy%20tranquilo.mp3" },
    { title: "Fidelidad grande es tu fidelidad", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Fidelidad%20grande%20es%20tu%20fidelidad.mp3" },
    { title: "Ganarlos a todos", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Ganarlos%20a%20todos.mp3" },
    { title: "Jesus adrian romero marcela gandara lilly goodman oscar medina alex campos mejores exitos", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Jesus%20adrian%20romero%20marcela%20gandara%20lilly%20goodman%20oscar%20medina%20alex%20campos%20mejores%20exitos%2020266.mp3" },
    { title: "Llevame a la cruz nadie igual", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Llevame%20a%20la%20cruz%20nadie%20igual.mp3" },
    { title: "Lo haras otra vez", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Lo%20haras%20otra%20vez%20do%20it%20again.mp3" },
    { title: "Luz y sal", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Luz%20y%20sal.mp3" },
    { title: "Me cubre tu gracia", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Me%20cubre%20tu%20gracia.mp3" },
    { title: "Mi entorno", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Mi%20entorno.mp3" },
    { title: "Mi gps", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Mi%20gps.mp3" },
    { title: "Nada mas yeshua", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Nada%20mas%20yeshua.mp3" },
    { title: "Niko eme mesias version urbana", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Niko%20eme%20mesias%20version%20urbana%20worshipurbano.mp3" },
    { title: "Oceanos", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Oceanos.mp3" },
    { title: "Oceans spanish version kevz hillsong", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Oceans%20spanish%20version%20kevz%20hillsong.mp3" },
    { title: "Oscar medina lo mejor de lo mejor grandes exitos", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Oscar%20medina%20lo%20mejor%20de%20lo%20mejor%20grandes%20exitos%C2%B6oscar%20medina%20exitos%20la%20mejor%20musica%20cristiana8.mp3" },
    { title: "Paz en la tormenta", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Paz%20en%20la%20tormenta.mp3" },
    { title: "Probar y verte deseo eterno", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Probar%20y%20verte%20deseo%20eterno.mp3" },
    { title: "Quien dijo miedo", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Quien%20dijo%20miedo.mp3" },
    { title: "Quiero conocer a jesus yeshua nuestro dios", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Quiero%20conocer%20a%20jesus%20yeshua%20nuestro%20dios.mp3" },
    { title: "Quiero levantar mis manos", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Quiero%20levantar%20mis%20manos.mp3" },
    { title: "Sabaoth drill", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Sabaoth%20drill.mp3" },
    { title: "Santo por siempre juntas x crys x priscilla bueno", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Santo%20por%20siempre%20juntas%20x%20crys%20x%20priscilla%20bueno.mp3" },
    { title: "Se quedo conmigo", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Se%20quedo%20conmigo.mp3" },
    { title: "Si estoy contigo", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Si%20estoy%20contigo.mp3" },
    { title: "Solo cree mambo", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Solo%20cree%20mambo.mp3" },
    { title: "Solo cree", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Solo%20cree.mp3" },
    { title: "Soy soldado", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Soy%20soldado.mp3" },
    { title: "Te quiero", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Te%20quiero.mp3" },
    { title: "Todo va a estar bien las dominguez", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Todo%20va%20a%20estar%20bien%20las%20dominguez.mp3" },
    { title: "Todo y nada", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Todo%20y%20nada.mp3" },
    { title: "Tu proveeras", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Tu%20proveeras.mp3" },
    { title: "Tus pasos", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Tus%20pasos.mp3" },
    { title: "Un viaje largo", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Un%20viaje%20largo.mp3" },
    { title: "Vasijas rotas sublime gracia siovera", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Vasijas%20rotas%20sublime%20gracia%20siovera%20broken%20vessels%20amazing%20grace%20hillsong%20worship%20espanol.mp3" },
    { title: "Vuelvo", url: "https://raw.githubusercontent.com/bryan7896/musica3/main/Vuelvo.mp3" },
    { title: "A dios sea la gloria gospel 1945 himno antiguo", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/A%20dios%20sea%20la%20gloria%20gospel%201945%20himno%20antiguo.mp3" },
    { title: "A solas al huerto yo voy himno majestuoso 256 musica y interp enoc sangama", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/A%20solas%20al%20huerto%20yo%20voy%20himno%20majestuoso%20256%20musica%20y%20interp%20enoc%20sangama.mp3" },
    { title: "Abre mis ojos a la luz con himnos cristianos antiguos y hermosos", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Abre%20mis%20ojos%20a%20la%20luz%20con%20himnos%20cristianos%20antiguos%20y%20hermosos.mp3" },
    { title: "Adoradle adoradle adorad al salvador con himnos cristianos antiguos", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Adoradle%20adoradle%20adorad%20al%20salvador%20con%20himnos%20cristianos%20antiguos.mp3" },
    { title: "All things are possible hillsong worship", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/All%20things%20are%20possible%20hillsong%20worship.mp3" },
    { title: "Anos mi alma en vanidad vivio con himnos cristianos antiguos", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Anos%20mi%20alma%20en%20vanidad%20vivio%20con%20himnos%20cristianos%20antiguos.mp3" },
    { title: "Ante ti con gozo", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Ante%20ti%20con%20gozo.mp3" },
    { title: "Asi como david danzaba", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Asi%20como%20david%20danzaba.mp3" },
    { title: "Aunque el gigante se encuentre alla", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Aunque%20el%20gigante%20se%20encuentre%20alla.mp3" },
    { title: "Cantare al senor por siempre", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Cantare%20al%20senor%20por%20siempre.mp3" },
    { title: "Cantos de jubilo jaime murrell musicacristiana alabanza cantosdejubilo jaimemurrell", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Cantos%20de%20jubilo%20jaime%20murrell%20musicacristiana%20alabanza%20cantosdejubilo%20jaimemurrell.mp3" },
    { title: "Castillo fuerte es nuestro dios gracia soberana musica", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Castillo%20fuerte%20es%20nuestro%20dios%20gracia%20soberana%20musica.mp3" },
    { title: "Castillo fuerte es nuestro dios", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Castillo%20fuerte%20es%20nuestro%20dios.mp3" },
    { title: "Cerca de ti senor himno majestuoso 429", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Cerca%20de%20ti%20senor%20himno%20majestuoso%20429.mp3" },
    { title: "Cristo mi camino guio con himnos cristianos antiguos", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Cristo%20mi%20camino%20guio%20con%20himnos%20cristianos%20antiguos.mp3" },
    { title: "Cristo yo creo en ti crystal lewis", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Cristo%20yo%20creo%20en%20ti%20crystal%20lewis.mp3" },
    { title: "Cuan gloriosa sera la manana gospel 1945 himno antiguo", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Cuan%20gloriosa%20sera%20la%20manana%20gospel%201945%20himno%20antiguo.mp3" },
    { title: "Cuando alla se pase lista gospel 1945 himno antiguo", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Cuando%20alla%20se%20pase%20lista%20gospel%201945%20himno%20antiguo.mp3" },
    { title: "Cuenta tus bendiciones con himno sud", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Cuenta%20tus%20bendiciones%20con%20himno%20sud.mp3" },
    { title: "Danilo montero dulce refugio es por tu espritump4", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Danilo%20montero%20dulce%20refugio%20es%20por%20tu%20espritump4.mp3" },
    { title: "Danilo montero inedito 1994 te dare lo mejor by matixalfa", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Danilo%20montero%20inedito%201994%20te%20dare%20lo%20mejor%20by%20matixalfa.mp3" },
    { title: "Danza hebrea levantate senor bueno es roni roni", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Danza%20hebrea%20levantate%20senor%20bueno%20es%20roni%20roni.mp3" },
    { title: "Decidido luis santiago", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Decidido%20luis%20santiago.mp3" },
    { title: "Edgar rocha al que esta sentado en el trono", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Edgar%20rocha%20al%20que%20esta%20sentado%20en%20el%20trono.mp3" },
    { title: "El gozo juan carlos alvarado 1993", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/El%20gozo%20juan%20carlos%20alvarado%201993.mp3" },
    { title: "El me levantara con himnos cristianos antiguos hermosos", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/El%20me%20levantara%20con%20himnos%20cristianos%20antiguos%20hermosos.mp3" },
    { title: "El rey ya viene gospel 1945 himno antiguo", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/El%20rey%20ya%20viene%20gospel%201945%20himno%20antiguo.mp3" },
    { title: "En la vina del senor gospel 1945 himno antiguo", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/En%20la%20vina%20del%20senor%20gospel%201945%20himno%20antiguo.mp3" },
    { title: "Es por jesus", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Es%20por%20jesus.mp3" },
    { title: "Escucharte hablar marcos witt", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Escucharte%20hablar%20marcos%20witt.mp3" },
    { title: "Firmes y adelante gospel 1945 himno antiguo", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Firmes%20y%20adelante%20gospel%201945%20himno%20antiguo.mp3" },
    { title: "Firmes y adelante l himnos y coros l bethel television", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Firmes%20y%20adelante%20l%20himnos%20y%20coros%20l%20bethel%20television.mp3" },
    { title: "Gloria gloria aleluya con himnos cristianos de siempre", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Gloria%20gloria%20aleluya%20con%20himnos%20cristianos%20de%20siempre.mp3" },
    { title: "Glorificate video original 1993 juan carlos alvarado", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Glorificate%20video%20original%201993%20juan%20carlos%20alvarado.mp3" },
    { title: "Grande es tu fidelidad oh tu fidelidad su presencia great is thy faithfulness espanol", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Grande%20es%20tu%20fidelidad%20oh%20tu%20fidelidad%20su%20presencia%20great%20is%20thy%20faithfulness%20espanol.mp3" },
    { title: "Grande gozo gospel 1945 himno antiguo", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Grande%20gozo%20gospel%201945%20himno%20antiguo.mp3" },
    { title: "Has aumentado danilo montero", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Has%20aumentado%20danilo%20montero.mp3" },
    { title: "Hay poder gospel 1945 himno antiguo", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Hay%20poder%20gospel%201945%20himno%20antiguo.mp3" },
    { title: "Hay un canto nuevo en mi ser himno 363 nuevo himnario adventista ¶", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Hay%20un%20canto%20nuevo%20en%20mi%20ser%20himno%20363%20nuevo%20himnario%20adventista%20%B6.mp3" },
    { title: "Himno 230 grande es tu fidelidad", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Himno%20230%20grande%20es%20tu%20fidelidad.mp3" },
    { title: "Himno adventista 097 en el monte calvario", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Himno%20adventista%20097%20en%20el%20monte%20calvario.mp3" },
    { title: "Himno sublime gracia", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Himno%20sublime%20gracia.mp3" },
    { title: "Himnos de gloria n 53 en la cruz", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Himnos%20de%20gloria%20n%2053%20en%20la%20cruz.mp3" },
    { title: "Jaci velasquez un lugar celestial", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Jaci%20velasquez%20un%20lugar%20celestial.mp3" },
    { title: "Juan carlos alvarado mi mejor adoracion no basta", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Juan%20carlos%20alvarado%20mi%20mejor%20adoracion%20no%20basta.mp3" },
    { title: "Juan carlos alvarado santo es el senor soy deudor", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Juan%20carlos%20alvarado%20santo%20es%20el%20senor%20soy%20deudor.mp3" },
    { title: "La danza del rey david remolineando", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/La%20danza%20del%20rey%20david%20remolineando.mp3" },
    { title: "Lavame en tu sangre salvador entera consagracion gospel 1945 himno antiguo", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Lavame%20en%20tu%20sangre%20salvador%20entera%20consagracion%20gospel%201945%20himno%20antiguo.mp3" },
    { title: "Love you so much hillsong", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Love%20you%20so%20much%20hillsong.mp3" },
    { title: "Manuel bonilla en el monte calvario videolyric", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Manuel%20bonilla%20en%20el%20monte%20calvario%20videolyric.mp3" },
    { title: "Maravillosa gracia himno majestuoso 147", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Maravillosa%20gracia%20himno%20majestuoso%20147.mp3" },
    { title: "Marcos barrientos el camino del senor es perfecto", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Marcos%20barrientos%20el%20camino%20del%20senor%20es%20perfecto.mp3" },
    { title: "Marcos witt con tu sangre", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Marcos%20witt%20con%20tu%20sangre.mp3" },
    { title: "Marcos witt dios al mundo amo", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Marcos%20witt%20dios%20al%20mundo%20amo.mp3" },
    { title: "Marcos witt quiero levantar mis manos recuerdos", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Marcos%20witt%20quiero%20levantar%20mis%20manos%20recuerdos.mp3" },
    { title: "Marcos witt tu fidelidad videolyric", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Marcos%20witt%20tu%20fidelidad%20videolyric.mp3" },
    { title: "Marcos witt tu fidelidad", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Marcos%20witt%20tu%20fidelidad.mp3" },
    { title: "Mas alla del sol gospel 1945 himno antiguo", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Mas%20alla%20del%20sol%20gospel%201945%20himno%20antiguo.mp3" },
    { title: "Mi canto y fortaleza", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Mi%20canto%20y%20fortaleza.mp3" },
    { title: "Miguel cassina el vive", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Miguel%20cassina%20el%20vive.mp3" },
    { title: "Motivo de mi cancion", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Motivo%20de%20mi%20cancion.mp3" },
    { title: "No cambiaria marcos witt", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/No%20cambiaria%20marcos%20witt.mp3" },
    { title: "No puede el mundo ser mi hogar gospel 1945 himno antiguo", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/No%20puede%20el%20mundo%20ser%20mi%20hogar%20gospel%201945%20himno%20antiguo.mp3" },
    { title: "Oh moradora de sion jaime murrel", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Oh%20moradora%20de%20sion%20jaime%20murrel.mp3" },
    { title: "Oh que amigo nos es cristo", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Oh%20que%20amigo%20nos%20es%20cristo.mp3" },
    { title: "Oh tu fidelidad gospel 1945 himno antiguo", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Oh%20tu%20fidelidad%20gospel%201945%20himno%20antiguo.mp3" },
    { title: "Oh tu fidelidad himno cristiano", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Oh%20tu%20fidelidad%20himno%20cristiano.mp3" },
    { title: "Omnipotente", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Omnipotente.mp3" },
    { title: "Palabra en accion va ver un avivamiento en este lugar", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Palabra%20en%20accion%20va%20ver%20un%20avivamiento%20en%20este%20lugar.mp3" },
    { title: "Paz en la tierra rene gonzales", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Paz%20en%20la%20tierra%20rene%20gonzales.mp3" },
    { title: "Pecador ven a cristo jesus con himnos cristianos antiguos", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Pecador%20ven%20a%20cristo%20jesus%20con%20himnos%20cristianos%20antiguos.mp3" },
    { title: "People get free hillsong worship", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/People%20get%20free%20hillsong%20worship.mp3" },
    { title: "Porque el vive gospel 1945 himno antiguo", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Porque%20el%20vive%20gospel%201945%20himno%20antiguo.mp3" },
    { title: "Quien nos separara", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Quien%20nos%20separara.mp3" },
    { title: "Quiero llenar tu trono de alabanza con", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Quiero%20llenar%20tu%20trono%20de%20alabanza%20con.mp3" },
    { title: "Rey de toda nacion", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Rey%20de%20toda%20nacion.mp3" },
    { title: "Rojo jardin de rosas", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Rojo%20jardin%20de%20rosas.mp3" },
    { title: "Rojo solo tu", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Rojo%20solo%20tu.mp3" },
    { title: "Santo santo santo himno majestuoso 64 y bautista 1 musica y", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Santo%20santo%20santo%20himno%20majestuoso%2064%20y%20bautista%201%20musica%20y.mp3" },
    { title: "Santo santo santo", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Santo%20santo%20santo.mp3" },
    { title: "Sentado en su trono danilo montero", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Sentado%20en%20su%20trono%20danilo%20montero.mp3" },
    { title: "Sigueme danilo montero", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Sigueme%20danilo%20montero.mp3" },
    { title: "Solo de jesus la sangre gospel 1945 himno antiguo", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Solo%20de%20jesus%20la%20sangre%20gospel%201945%20himno%20antiguo.mp3" },
    { title: "Su nombre de guerra es jehova", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Su%20nombre%20de%20guerra%20es%20jehova.mp3" },
    { title: "Te alabamos senor alejandro del bosque con", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Te%20alabamos%20senor%20alejandro%20del%20bosque%20con.mp3" },
    { title: "Te alabare", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Te%20alabare.mp3" },
    { title: "Te anhelo 1992 marcos witt inedito", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Te%20anhelo%201992%20marcos%20witt%20inedito.mp3" },
    { title: "Te dare lo mejor del trigo torre fuerte jos luis torres", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Te%20dare%20lo%20mejor%20del%20trigo%20torre%20fuerte%20jos%20luis%20torres.mp3" },
    { title: "Te exaltamos marcos witt proyecto aa", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Te%20exaltamos%20marcos%20witt%20proyecto%20aa.mp3" },
    { title: "Te pido la paz jaime murrell primera version musicacristiana tepidolapaz jaimemurrell paz", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Te%20pido%20la%20paz%20jaime%20murrell%20primera%20version%20musicacristiana%20tepidolapaz%20jaimemurrell%20paz.mp3" },
    { title: "This is how we overcome by hillsong credit to the owners video", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/This%20is%20how%20we%20overcome%20by%20hillsong%20credit%20to%20the%20owners%20video.mp3" },
    { title: "Torre fuerte ex musico de luis miguel serenata espiritual balada cristiana", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Torre%20fuerte%20ex%20musico%20de%20luis%20miguel%20serenata%20espiritual%20balada%20cristiana.mp3" },
    { title: "Tu palabra", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Tu%20palabra.mp3" },
    { title: "Tu por mi torre fuerte hq", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Tu%20por%20mi%20torre%20fuerte%20hq.mp3" },
    { title: "Ven a el pecador ven al dulce jesus gospel 1945 himno antiguo", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Ven%20a%20el%20pecador%20ven%20al%20dulce%20jesus%20gospel%201945%20himno%20antiguo.mp3" },
    { title: "Ven espiritu ven y llename senor con tu preciosa uncion con", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Ven%20espiritu%20ven%20y%20llename%20senor%20con%20tu%20preciosa%20uncion%20con.mp3" },
    { title: "Yo quiero mas de ti jaime murrell yoquieromasdeti jaimemurrell videooficial", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Yo%20quiero%20mas%20de%20ti%20jaime%20murrell%20yoquieromasdeti%20jaimemurrell%20videooficial.mp3" },
    { title: "Yo vivo por fe con himnos cistianos antiguos", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/Yo%20vivo%20por%20fe%20con%20himnos%20cistianos%20antiguos.mp3" },
    { title: "al que esta sentado en el trono marcos witt album poderoso grabacion fallida 1992", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/al%20que%20esta%20sentado%20en%20el%20trono%20marcos%20witt%20album%20poderoso%20grabacion%20fallida%201992.mp3" },
    { title: "dulce oracion", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/dulce%20oracion.mp3" },
    { title: "es por tu espiritu", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/es%20por%20tu%20espiritu.mp3" },
    { title: "eterna roca es mi jesus", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/eterna%20roca%20es%20mi%20jesus.mp3" },
    { title: "firmes y adelante", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/firmes%20y%20adelante.mp3" },
    { title: "has ganado la victoria marco barrientos", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/has%20ganado%20la%20victoria%20marco%20barrientos.mp3" },
    { title: "junto a la cruz", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/junto%20a%20la%20cruz.mp3" },
    { title: "marco barrientos en majestad album muestrame tu gloria", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/marco%20barrientos%20en%20majestad%20album%20muestrame%20tu%20gloria.mp3" },
    { title: "mas cerca oh dios de ti", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/mas%20cerca%20oh%20dios%20de%20ti.mp3" },
    { title: "me gusta estar en tu casa", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/me%20gusta%20estar%20en%20tu%20casa.mp3" },
    { title: "porque el senor todopoderoso reina marco barrientos en ti 1991", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/porque%20el%20senor%20todopoderoso%20reina%20marco%20barrientos%20en%20ti%201991.mp3" },
    { title: "sera llena la tierra marco barrientos en ti 1991", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/sera%20llena%20la%20tierra%20marco%20barrientos%20en%20ti%201991.mp3" },
    { title: "tu habitas marco barrientos en ti 1991", url: "https://raw.githubusercontent.com/bryan7896/musica4/main/tu%20habitas%20marco%20barrientos%20en%20ti%201991.mp3" }
];

const MIAS = [
    { title: "EL QUE NO DUERME v1", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/Music/EL%20QUE%20NO%20DUERME%20v1.mp3" },
    { title: "Contigo todo pesa menos", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/Music/Contigo%20todo%20pesa%20menos.mp3" },
    { title: "EL QUE NO DUERME v2", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/Music/EL%20QUE%20NO%20DUERME%20v2.mp3" },
    { title: "El desorden perfecto", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/Music/El%20desorden%20perfecto.mp3" },
    { title: "El reloj se para", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/Music/El%20reloj%20se%20para.mp3" },
    { title: "El tamaño de tu mano", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/Music/El%20tama%C3%B1o%20de%20tu%20mano.mp3" },
    { title: "Mi lugar en el mundo", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/Music/Mi%20lugar%20en%20el%20mundo.mp3" },
    { title: "Mi princesa", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/Music/Mi%20princesa.mp3" },
    { title: "También sus espinas", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/Music/Tambi%C3%A9n%20sus%20espinas.mp3" },
    { title: "Te amo", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/Music/Te%20amo.mp3" },
    { title: "Todavía me sorprende", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/Music/Todav%C3%ADa%20me%20sorprende.mp3" },
    { title: "Tu nombre es mi respiración", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/Music/Tu%20nombre%20es%20mi%20respiraci%C3%B3n.mp3" },
    { title: "Mi lugar favorito", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/Music/Mi%20lugar%20favorito.mp3" }
];

const GYM = [
    { title: "Adrenalina hard techno rave", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/adrenalina%20%20hard%20techno%20rave.mp3" },
    { title: "Alessia Cara - Here", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/alessia%20cara%20-%20here.mp3" },
    { title: "Ballintekk", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/ballintekk.mp3" },
    { title: "Billie Eilish - L'amour de ma vie", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/billie%20eilish%20-%20lamour%20de%20ma%20vie.mp3" },
    { title: "Boney M. - Rasputin", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/boney%20m.%20-%20rasputin.mp3" },
    { title: "Bring Me The Horizon - Can You Feel My Heart", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/can%20you%20feel%20my%20heart%20-%20bring%20me%20the%20horizon.mp3" },
    { title: "Michael Jackson - Chicago", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/chicago%20-%20michael%20jackson.mp3" },
    { title: "Danny - Take Me", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/d%20a%20n%20n%20y%20-%20take%20me.mp3" },
    { title: "Esta canción da mucha aura", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/esta%20cancion%20da%20mucha%20aura.mp3" },
    { title: "First Blood", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/first%20blood.mp3" },
    { title: "Fujii Kaze - Shinunoga E-Wa", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/fujii%20kaze%20-%20shinunoga%20e-wa.mp3" },
    { title: "Hard Techno - Voices In My Head", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/hard%20techno%20%20voices%20in%20my%20head.mp3" },
    { title: "Infeed - Freedom Inside Your Illness", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/infeed%20-%20freedom%20inside%20your%20illness.mp3" },
    { title: "Jeremy Zucker - Comethru", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/jeremy%20zucker%20-%20comethru.mp3" },
    { title: "Josean Log - Kaguya-sama Love Is War", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/kaguya-sama_%20love%20is%20waramvdoma%20%20josean%20log.mp3" },
    { title: "Kehlani - Gangsta", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/kehlani%20-%20gangsta.mp3" },
    { title: "Kordhell - Murder In My Mind (Speed Up)", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/kordhell%20-%20murder%20in%20my%20mind%20%20speed%20up.mp3" },
    { title: "MTG Chihiro", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/mtg%20chihiro.mp3" },
    { title: "Ogryzek - Aura", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/ogryzek%20-%20aura.mp3" },
    { title: "Olivia Rodrigo - Honeybee", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/olivia%20rodrigo%20-%20honeybee.mp3" },
    { title: "Skillet - Hero", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/skillet%20-%20hero.mp3" },
    { title: "Skillet - Monster", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/skillet%20-%20monster.mp3" },
    { title: "Skillet - Not Gonna Die", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/skillet%20-%20not%20gonna%20die.mp3" },
    { title: "Skrillex - Bangarang (feat. Sirah)", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/skrillex%20-%20bangarang%20feat.%20sirah.mp3" },
    { title: "Skrillex - First Of The Year", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/skrillex%20-%20first%20of%20the%20year.mp3" },
    { title: "Skrillex - Kyoto", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/skrillex%20-%20kyoto.mp3" },
    { title: "Skrillex - Rock N Roll", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/skrillex%20-%20rock%20n%20roll.mp3" },
    { title: "Skrillex & Damian Jr. Gong Marley - Make It Bun Dem", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/skrillex%20and%20damian%20jr.%20gong%20marley%20-%20make%20it%20bun%20dem.mp3" },
    { title: "Super Smash Bros Brawl Drill Remix - By Shae OT", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/super%20smash%20bros%20brawl%20drill%20remix%20%20by%20shae%20ot.mp3" },
    { title: "Tell Em x Killin On Demand (TikTok)", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/tell%20em%20x%20killin%20on%20demand%20tiktok.mp3" },
    { title: "Twenty One Pilots - Heathens", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/twenty%20one%20pilots%20-%20heathens.mp3" },
    { title: "Unaverage Gang - Underworld", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/unaverage%20gang%20-%20underworld.mp3" },
    { title: "Xvallarix - Ballintekk", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/xvallarix%20-%20ballintekk.mp3" },
    { title: "ACDC - BACK IN BLACK", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/ACDC%20-%20BACK%20IN%20BLACK.mp3" },
    { title: "Armin van Buuren - Turn It Up.mp3", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/Armin%20van%20Buuren%20-%20Turn%20It%20Up.mp3" },
    { title: "Bel Mercy feat. Nokia.mp3", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/Bel%20Mercy%20feat.%20Nokia.mp3" },
    { title: "Bel Mercy.mp3", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/Bel%20Mercy.mp3" },
    { title: "Benny Benassi - Satisfaction.mp3", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/Benny%20Benassi%20-%20Satisfaction.mp3" },
    { title: "Black Eyed Peas - My Humps.mp3", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/Black%20Eyed%20Peas%20-%20My%20Humps.mp3" },
    { title: "FOVOS - Feel The Rhythm.mp3", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/FOVOS%20-%20Feel%20The%20Rhythm.mp3" },
    { title: "Gonzi - BASSKILLER.mp3", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/Gonzi%20-%20BASSKILLER.mp3" },
    { title: "Guns N Roses - Welcome To The Jungle.mp3", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/Guns%20N%20Roses%20-%20Welcome%20To%20The%20Jungle.mp3" },
    { title: "KISS  I Was Made For Lovin You.mp3", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/KISS%20%20I%20Was%20Made%20For%20Lovin%20You.mp3" },
    { title: "LICK IT.mp3", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/LICK%20IT.mp3" },
    { title: "Maneskin - MAMMAMIA.mp3", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/Maneskin%20-%20MAMMAMIA.mp3" },
    { title: "Måneskin - GOSSIP ft. Tom Morello Sub español  Lyrics.mp3", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/M%C3%A5neskin%20-%20GOSSIP%20ft.%20Tom%20Morello%20Sub%20espa%C3%B1ol%20%20Lyrics.mp3" },
    { title: "Not Broken  CortexUS.mp3", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/Not%20Broken%20%20CortexUS.mp3" },
    { title: "Rammstein - Du Hast.mp3", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/Rammstein%20-%20Du%20Hast.mp3" },
    { title: "Sweet Child O Mine.mp3", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/Sweet%20Child%20O%20Mine.mp3" },
    { title: "TECHNO  NO BATIDA.mp3", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/TECHNO%20%20NO%20BATIDA.mp3" },
    { title: "The Black Eyed Peas - The Time.mp3", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/The%20Black%20Eyed%20Peas%20-%20The%20Time.mp3" },
    { title: "Toby DEE, Tony Richard, SANE - Toccata.mp3", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/MusicaGym/Toby%20DEE,%20Tony%20Richard,%20SANE%20-%20Toccata.mp3" },
    { title: "El cuarteto de nos enamorado tuyo", url: "https://raw.githubusercontent.com/bryan7896/MusicBryan/main/Music/El%20cuarteto%20de%20nos%20enamorado%20tuyo.mp3" },
];